export default {
    GET_USER_DATA: "GET_USER_DATA",
    DATA_LOADING: "DATA_LOADING",
    GET_TOKEN: "GET_TOKEN",
    SET_ERRORS: "SET_ERRORS",
    DISABLE_BUTTON: "DISABLE_BUTTON",
    GET_PRODUCTS : "GET_PRODUCTS",
    GET_USER_FAVORITES: "GET_USER_FAVORITES",
    GET_USER_CART: "GET_USER_CART",
    FAVORITE_PRODUCT: "FAVORITE_PRODUCT",
    UNFAVORITE_PRODUCT: "UNFAVORITE_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    GET_PRODUCT_ID: "GET_PRODUCT_ID",
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    CLEAR_CART: "CLEAR_CART",
    ADD_TOTALS: "ADD_TOTALS"

};